### ISSUE TITLE
SyntaxError on docker run

### ISSUE THREAD

**Issue by miku** [finc/docker-vufind2#6]
Just tried to follow the [README](https://github.com/finc/docker-vufind2) with local Docker Version 17.12.0-ce-mac47 (21805):

```shell
$ docker run --name vufind -v `pwd`:/usr/local/vufind2 -P docker.io/ubleipzig/vufind2
Unable to find image 'ubleipzig/vufind2:latest' locally
latest: Pulling from ubleipzig/vufind2
b65f32901846: Pull complete
6c13147b9cf8: Pull complete
02bc56979a81: Pull complete
009257db5006: Pull complete
7198e95f37fd: Pull complete
ce86e19142a4: Pull complete
ed3411bee7af: Pull complete
0ae8f8cbd43a: Pull complete
36e314155206: Pull complete
36b771ab7c55: Pull complete
ea7d976755dc: Pull complete
c43a3627c2c1: Pull complete
ef8890aa74f5: Pull complete
5fea41daa74e: Pull complete
885f78d207fc: Pull complete
cc66641232b6: Pull complete
Digest: sha256:0eb0f348322a897dcbf11aec6a05387e64503a045cf6f1f2b0bb5ed4b687e676
Status: Downloaded newer image for ubleipzig/vufind2:latest
Setting up runtime environment...
Setting up 00-devtools...
Setting up 01-appuser-uid...
Setting app user to UID:1000 and GID:1000 ...
Setting up 02-mysqld...
Installing database...
Starting MySQL server...
Waiting for database server to accept connections...
Creating debian-sys-maint user...
Granting root permission from Docker Host ...
Setting root user password
Warning: Using a password on the command line interface can be insecure.
Setting up MySQL-Server for autostart ...
Setting up 03-apache2...
Enabling module ssl.
See /usr/share/doc/apache2.2-common/README.Debian.gz on how to configure SSL and create self-signed certificates.
Enabling module rewrite.
Enabling module suexec.
Module fcgid already enabled
Enabling module shib2.
To activate the new configuration, you need to run:
  service apache2 restart
Enabling site 99-app.
Enabling site default-ssl.
To activate the new configuration, you need to run:
  service apache2 reload
Setting up 04-nullmailer...
Setting up 05-php...
Setting up 06-shibboleth...
Setting up 60-solr...
Setting up 70-npm...
Installing locally required npm packages ...
npm WARN npm npm does not support Node.js v0.10.29
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@3.13.1 install /usr/local/vufind2/node_modules/node-sass
> node scripts/install.js


/usr/local/vufind2/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/vufind2/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
vufind@4.1.1 /usr/local/vufind2
+-- UNMET PEER DEPENDENCY grunt@1.0.1
| +-- coffee-script@1.10.0
| +-- dateformat@1.0.12
| | +-- get-stdin@4.0.1
| | `-- meow@3.7.0
| |   +-- camelcase-keys@2.1.0
| |   | `-- camelcase@2.1.1
| |   +-- decamelize@1.2.0
| |   +-- loud-rejection@1.6.0
| |   | +-- currently-unhandled@0.4.1
| |   | | `-- array-find-index@1.0.2
| |   | `-- signal-exit@3.0.2
| |   +-- map-obj@1.0.1
| |   +-- minimist@1.2.0
| |   +-- normalize-package-data@2.4.0
| |   | +-- hosted-git-info@2.5.0
| |   | +-- is-builtin-module@1.0.0
| |   | | `-- builtin-modules@1.1.1
| |   | +-- semver@5.5.0
| |   | `-- validate-npm-package-license@3.0.1
| |   |   +-- spdx-correct@1.0.2
| |   |   | `-- spdx-license-ids@1.2.2
| |   |   `-- spdx-expression-parse@1.0.4
| |   +-- object-assign@4.1.1
| |   +-- read-pkg-up@1.0.1
| |   | +-- find-up@1.1.2
| |   | | +-- path-exists@2.1.0
| |   | | `-- pinkie-promise@2.0.1
| |   | |   `-- pinkie@2.0.4
| |   | `-- read-pkg@1.1.0
| |   |   +-- load-json-file@1.1.0
| |   |   | +-- parse-json@2.2.0
| |   |   | | `-- error-ex@1.3.1
| |   |   | |   `-- is-arrayish@0.2.1
| |   |   | +-- pify@2.3.0
| |   |   | `-- strip-bom@2.0.0
| |   |   |   `-- is-utf8@0.2.1
| |   |   `-- path-type@1.1.0
| |   +-- redent@1.0.0
| |   | +-- indent-string@2.1.0
| |   | | `-- repeating@2.0.1
| |   | |   `-- is-finite@1.0.2
| |   | |     `-- number-is-nan@1.0.1
| |   | `-- strip-indent@1.0.1
| |   `-- trim-newlines@1.0.0
| +-- eventemitter2@0.4.14
| +-- exit@0.1.2
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| +-- glob@7.0.6
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | `-- once@1.4.0
| +-- grunt-cli@1.2.0
| | `-- resolve@1.1.7
| +-- grunt-known-options@1.1.0
| +-- grunt-legacy-log@1.0.0
| | +-- colors@1.1.2
| | +-- grunt-legacy-log-utils@1.0.0
| | | `-- lodash@4.3.0
| | +-- hooker@0.2.3
| | +-- lodash@3.10.1
| | `-- underscore.string@3.2.3
| +-- grunt-legacy-util@1.0.0
| | +-- getobject@0.1.0
| | +-- lodash@4.3.0
| | `-- which@1.2.14
| |   `-- isexe@2.0.0
| +-- iconv-lite@0.4.19
| +-- js-yaml@3.5.5
| | +-- argparse@1.0.9
| | | `-- sprintf-js@1.0.3
| | `-- esprima@2.7.3
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.8
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- nopt@3.0.6
| | `-- abbrev@1.1.1
| +-- path-is-absolute@1.0.1
| `-- rimraf@2.2.8
+-- grunt-contrib-less@1.3.0
| +-- async@1.5.2
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- less@2.6.1
| | +-- errno@0.1.6
| | | `-- prr@1.0.1
| | +-- graceful-fs@4.1.11
| | +-- image-size@0.4.0
| | +-- mime@1.6.0
| | +-- mkdirp@0.5.1
| | | `-- minimist@0.0.8
| | +-- promise@7.3.1
| | | `-- asap@2.0.6
| | +-- request@2.83.0
| | | +-- aws-sign2@0.7.0
| | | +-- aws4@1.6.0
| | | +-- caseless@0.12.0
| | | +-- combined-stream@1.0.5
| | | | `-- delayed-stream@1.0.0
| | | +-- extend@3.0.1
| | | +-- forever-agent@0.6.1
| | | +-- form-data@2.3.1
| | | | `-- asynckit@0.4.0
| | | +-- har-validator@5.0.3
| | | | +-- ajv@5.5.2
| | | | | +-- co@4.6.0
| | | | | +-- fast-deep-equal@1.0.0
| | | | | +-- fast-json-stable-stringify@2.0.0
| | | | | `-- json-schema-traverse@0.3.1
| | | | `-- har-schema@2.0.0
| | | +-- hawk@6.0.2
| | | | +-- boom@4.3.1
| | | | +-- cryptiles@3.1.2
| | | | | `-- boom@5.2.0
| | | | +-- hoek@4.2.0
| | | | `-- sntp@2.1.0
| | | +-- http-signature@1.2.0
| | | | +-- assert-plus@1.0.0
| | | | +-- jsprim@1.4.1
| | | | | +-- extsprintf@1.3.0
| | | | | +-- json-schema@0.2.3
| | | | | `-- verror@1.10.0
| | | | |   `-- core-util-is@1.0.2
| | | | `-- sshpk@1.13.1
| | | |   +-- asn1@0.2.3
| | | |   +-- bcrypt-pbkdf@1.0.1
| | | |   +-- dashdash@1.14.1
| | | |   +-- ecc-jsbn@0.1.1
| | | |   +-- getpass@0.1.7
| | | |   +-- jsbn@0.1.1
| | | |   `-- tweetnacl@0.14.5
| | | +-- is-typedarray@1.0.0
| | | +-- isstream@0.1.2
| | | +-- json-stringify-safe@5.0.1
| | | +-- mime-types@2.1.17
| | | | `-- mime-db@1.30.0
| | | +-- oauth-sign@0.8.2
| | | +-- performance-now@2.1.0
| | | +-- qs@6.5.1
| | | +-- safe-buffer@5.1.1
| | | +-- stringstream@0.0.5
| | | +-- tough-cookie@2.3.3
| | | | `-- punycode@1.4.1
| | | +-- tunnel-agent@0.6.0
| | | `-- uuid@3.2.1
| | `-- source-map@0.5.7
| `-- lodash@4.17.4
+-- grunt-contrib-watch@0.6.1
| +-- async@0.2.10
| +-- gaze@0.5.2
| | `-- globule@0.1.0
| |   +-- glob@3.1.21
| |   | +-- graceful-fs@1.2.3
| |   | `-- inherits@1.0.2
| |   +-- lodash@1.0.2
| |   `-- minimatch@0.2.14
| |     +-- lru-cache@2.7.3
| |     `-- sigmund@1.0.1
| +-- lodash@2.4.2
| `-- tiny-lr-fork@0.0.5
|   +-- debug@0.7.4
|   +-- faye-websocket@0.4.4
|   +-- noptify@0.0.3
|   | `-- nopt@2.0.0
|   `-- qs@0.5.6
+-- grunt-less-to-sass@0.0.10
| `-- lodash@3.0.1
`-- jit-grunt@0.9.1

npm WARN jit-grunt@0.9.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-watch@0.6.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN vufind@4.1.1 No license field.
npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.29
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 8

npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dev/.npm/_logs/2018-01-18T12_27_29_615Z-debug.log
```

Docker ps shows:

```shell
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                      PORTS               NAMES
9afd0789444c        ubleipzig/vufind2   "/docker/entrypoint …"   About a minute ago   Exited (8) 22 seconds ago                       vufind
```

**Comment by useltmann** [comment]
this comes from *vufind2:latest* still referring to image-tag *vufind2:php_5.4*, which is not working for recent vufind versions since a while now. i fixed this by setting the image-tag *vufind2:latest* to *vufind2:php_5.6*

Btw. using *latest* is not recommended and should be discouraged unless you know what you do. Since vufind2 requires and recommends PHP 5.6 one fellow developer should always use an image providing this. There is a tag-list (here)[https://hub.docker.com/r/ubleipzig/vufind2/tags/] which shows all usable tags and  when they were last built.
In order to use a new image one has to remove all previous container-volumes and auto-created files by the containers applications (e.g. node_modules). Better do a `git clean` to remove all files not belonging to vufind's sources.

I know this image is far from ideal structured but right now it has to do since i am not working on vufind2 anymore and i have other things to do.
